# Generated by Django 4.2.26 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'geplant'), ('completed', 'vorbei')], default='planned', max_length=20),
        ),
    ]
