# Generated by Django 4.2.26 on 2025-11-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Schüler/Student'), ('parent', 'Parent'), ('tutor', 'Tutor')], default='student', max_length=20),
        ),
    ]
