# Generated by Django 4.2.26 on 2025-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ort',
            field=models.CharField(choices=[('library', 'Bibliothek'), ('at home', 'Beim Schüler/Studenten'), ('at brainboost', 'Beim mir'), ('online', 'online')], default='at home', max_length=20),
        ),
    ]
