# Generated by Django 4.2.26 on 2025-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lesson_ort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ort',
            field=models.CharField(choices=[('library', 'Bibliothek'), ('at home', 'Beim Schüler/Studenten'), ('at brainboost', 'Bei mir'), ('online', 'online')], default='at home', max_length=20),
        ),
    ]
