# Generated by Django 4.2.26 on 2025-11-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_lesson_ort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'verbose_name': 'Elternprofil', 'verbose_name_plural': 'Elternprofile'},
        ),
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fortschrittseintrag', 'verbose_name_plural': 'Fortschrittseinträge'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Schülerprofil', 'verbose_name_plural': 'Schülerprofile'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'verbose_name': 'Tutorprofil', 'verbose_name_plural': 'Tutorprofile'},
        ),
    ]
