# Generated by Django 4.2.26 on 2025-11-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lesson_options_alter_parentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'verbose_name': 'Elternteil', 'verbose_name_plural': 'Eltern'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Schüler/Student', 'verbose_name_plural': 'Schüler/Studenten'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutoren'},
        ),
    ]
