# Generated by Django 4.2.26 on 2025-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_parentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('planned', 'geplant'), ('completed', 'vorbei'), ('cancelled', 'storniert')], default='planned', max_length=20),
        ),
    ]
