# Generated by Django 4.2.26 on 2025-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studentprofile_address_studentprofile_library_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='ort',
            field=models.CharField(choices=[('library', 'Bibliothek Braunschweig'), ('library_wob', 'Bibliothek Wolfsburg'), ('at home', 'Beim Schüler/Studenten'), ('at brainboost', 'Bei mir'), ('online', 'online')], default='at home', max_length=20),
        ),
    ]
