# Generated by Django 4.2.26 on 2025-11-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lesson_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='subject',
            new_name='fach',
        ),
    ]
