# Generated by Django 4.2.26 on 2025-11-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_learningmaterial'),
        ('core', '0013_rename_subject_lesson_fach'),
    ]

    operations = [
    ]
