# Generated by Django 4.2.26 on 2026-03-11 08:25

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.tutor_template_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.tutorprofile')),
            ],
            options={
                'verbose_name': 'Vorlage',
                'verbose_name_plural': 'Vorlagen',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
