# Generated by Django 4.2.26 on 2026-03-11 09:41

from django.db import migrations, models


def assign_existing_tutors(apps, schema_editor):
    StudentProfile = apps.get_model("core", "StudentProfile")
    Lesson = apps.get_model("core", "Lesson")
    through_model = StudentProfile.assigned_tutors.through

    assignments = set(
        Lesson.objects.values_list("student_id", "tutor_id").distinct()
    )
    through_model.objects.bulk_create(
        [
            through_model(studentprofile_id=student_id, tutorprofile_id=tutor_id)
            for student_id, tutor_id in assignments
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_tutortemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_tutors',
            field=models.ManyToManyField(blank=True, related_name='assigned_students', to='core.tutorprofile'),
        ),
        migrations.RunPython(assign_existing_tutors, migrations.RunPython.noop),
    ]
