# Generated by Django 4.2.26 on 2026-03-11 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_studentprofile_assigned_tutors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressentry',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mitarbeit'),
        ),
    ]
