# Generated by Django 4.2.26 on 2026-03-11 10:07

from django.db import migrations, models
import django.db.models.deletion


def approve_existing_invoices(apps, schema_editor):
    Invoice = apps.get_model("core", "Invoice")
    for invoice in Invoice.objects.filter(approved_at__isnull=True):
        invoice.approved_at = invoice.uploaded_at
        invoice.approved_by_id = invoice.uploaded_by_id
        invoice.save(update_fields=["approved_at", "approved_by"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_progressentry_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_invoices', to='core.tutorprofile'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='assigned_tutors',
            field=models.ManyToManyField(blank=True, related_name='supervising_tutors', to='core.tutorprofile'),
        ),
        migrations.RunPython(approve_existing_invoices, migrations.RunPython.noop),
    ]
