# Generated by Django 4.2.26 on 2026-03-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_invoice_approved_at_invoice_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lernfortschrittseintrag', 'verbose_name_plural': 'Lernfortschrittseinträge'},
        ),
    ]
