# Generated by Django 4.2.26 on 2026-03-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_progressentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='related_task',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'task'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_solutions', to='core.learningmaterial', verbose_name='Zugehoerige Aufgabe'),
        ),
    ]
