# Generated by Django 4.2.26 on 2026-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_parentprofile_phone_number_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'SchülerIn/StudentIn', 'verbose_name_plural': 'SchülerInnen/StudentInnen'},
        ),
        migrations.AlterModelOptions(
            name='tutorprofile',
            options={'verbose_name': 'TutorIn', 'verbose_name_plural': 'TutorInnen'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_icon',
            field=models.CharField(blank=True, choices=[('', 'Kein Profil-Icon'), ('eagle', 'Adler'), ('shark', 'Hai'), ('lion', 'Löwe'), ('ant', 'Ameise')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'SchülerIn/StudentIn'), ('parent', 'Parent'), ('tutor', 'TutorIn')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ort',
            field=models.CharField(choices=[('library', 'Bibliothek Braunschweig'), ('library_wob', 'Bibliothek Wolfsburg'), ('at home', 'Bei SchülerIn/StudentIn'), ('at brainboost', 'Bei mir'), ('online', 'online')], default='at home', max_length=20),
        ),
    ]
