# Generated by Django 4.2.26 on 2026-03-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fach',
            field=models.CharField(choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('musik', 'Musik')], default='mathe', max_length=50),
        ),
    ]
