# Generated by Django 4.2.26 on 2026-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_lesson_fach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fach',
            field=models.CharField(choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik')], default='mathe', max_length=50),
        ),
    ]
