# Generated by Django 4.2.26 on 2026-03-12 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_lesson_fach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressentry',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mitarbeit'),
        ),
    ]
