# Generated by Django 4.2.26 on 2026-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_progressentry_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
