# Generated by Django 4.2.26 on 2026-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_tutorprofile_account_holder_tutorprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'bar'), ('bank_transfer', 'Überweisung'), ('online', 'online')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('open', 'offen'), ('paid', 'bezahlt')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
