# Generated by Django 4.2.26 on 2026-03-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_invoice_amount_total_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_invoice_payments', to='core.parentprofile'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('open', 'offen'), ('announced', 'angekündigt'), ('paid', 'bezahlt')], default='open', max_length=20),
        ),
    ]
