# Generated by Django 4.2.26 on 2026-03-14 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_invoice_payment_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='fach_2',
            field=models.CharField(blank=True, choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='fach_3',
            field=models.CharField(blank=True, choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='rating_fach_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mitarbeit Fach 2'),
        ),
        migrations.AddField(
            model_name='progressentry',
            name='rating_fach_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Mitarbeit Fach 3'),
        ),
    ]
