# Generated by Django 4.2.26 on 2026-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_lesson_fach_2_lesson_fach_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='fach',
            field=models.CharField(choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik'), ('spezifische_nachhilfe', 'SPEZIFISCHE NACHHILFE')], default='mathe', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fach_2',
            field=models.CharField(blank=True, choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik'), ('spezifische_nachhilfe', 'SPEZIFISCHE NACHHILFE')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='fach_3',
            field=models.CharField(blank=True, choices=[('mathe', 'Mathe'), ('deutsch', 'Deutsch'), ('englisch', 'Englisch'), ('chemie', 'Chemie'), ('biologie', 'Biologie'), ('erdkunde', 'Erdkunde'), ('physik', 'Physik'), ('sonstiges_mint', 'Sonstiges mathematisch-naturwissenschaftliches Fach'), ('franzoesisch', 'Französisch'), ('spanisch', 'Spanisch'), ('sonstiges_sprache', 'Sonstiges sprachliches Fach'), ('geschichte', 'Geschichte'), ('informatik', 'Informatik'), ('politik', 'Politik'), ('sonstiges_gesellschaft', 'Sonstiges gesellschaftliches Fach'), ('musik', 'Musik'), ('spezifische_nachhilfe', 'SPEZIFISCHE NACHHILFE')], default='', max_length=50),
        ),
    ]
