# Generated by Django 4.2.26 on 2026-03-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_lesson_fach_alter_lesson_fach_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='Nachhilfe in den kommenden Ferien?', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_surveys', to='core.tutorprofile')),
            ],
            options={
                'verbose_name': 'Umfrage',
                'verbose_name_plural': 'Umfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidaySurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('yes', 'Ja'), ('no', 'Nein')], default='', max_length=10)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_survey_responses', to='core.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_survey_responses', to='core.studentprofile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.holidaysurvey')),
            ],
            options={
                'verbose_name': 'Umfrageantwort',
                'verbose_name_plural': 'Umfrageantworten',
                'ordering': ['student__user__last_name', 'student__user__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='holidaysurveyresponse',
            constraint=models.UniqueConstraint(fields=('survey', 'student'), name='unique_holiday_survey_response_per_student'),
        ),
    ]
