# Generated by Django 4.2.26 on 2026-03-14 18:30

from django.db import migrations, models


def migrate_faq_audience_to_targets(apps, schema_editor):
    FAQItem = apps.get_model("core", "FAQItem")
    for item in FAQItem.objects.all():
        audience = getattr(item, "audience", "")
        item.show_for_parents = audience in {"parent", "both"}
        item.show_for_students = audience in {"student", "both"}
        item.show_for_tutors = False
        item.show_on_landing = False
        item.save(
            update_fields=[
                "show_for_parents",
                "show_for_students",
                "show_for_tutors",
                "show_on_landing",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_faqitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="faqitem",
            name="show_for_parents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="show_for_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="show_for_tutors",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="faqitem",
            name="show_on_landing",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            migrate_faq_audience_to_targets,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="faqitem",
            name="audience",
        ),
    ]
