# Generated by Django 4.2.26 on 2026-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_faqitem_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
