# Generated by Django 4.2.26 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_invoice_numbering_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("fixed", "EUR"), ("percent", "%")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
