# Generated by Django 4.2.26 on 2026-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_invoice_discount_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainBoostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('student', 'SchülerIn/StudentIn'), ('parent', 'Eltern'), ('tutor', 'TutorIn'), ('other', 'Sonstige')], max_length=20)),
                ('source', models.CharField(choices=[('email', 'E-Mail'), ('news', 'News'), ('landing', 'Startseite'), ('direct', 'Direkt')], default='direct', max_length=20)),
                ('what_is_needed', models.TextField(blank=True)),
                ('what_went_bad', models.TextField(blank=True)),
                ('wishes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BrainBoost Feedback',
                'verbose_name_plural': 'BrainBoost Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFeedbackReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('student', 'SchülerIn/StudentIn'), ('parent', 'Eltern'), ('tutor', 'TutorIn'), ('other', 'Sonstige')], max_length=20)),
                ('month', models.DateField(help_text='Monatserster, für den der Reminder gesendet wurde.')),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monatlicher Feedback-Reminder',
                'verbose_name_plural': 'Monatliche Feedback-Reminder',
                'ordering': ['-month', 'audience'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlyfeedbackreminderlog',
            constraint=models.UniqueConstraint(fields=('audience', 'month'), name='unique_monthly_feedback_reminder_per_audience_month'),
        ),
    ]
