# Generated by Django 4.2.26 on 2026-03-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_temporarytutorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytutorassignment',
            name='end_mode',
            field=models.CharField(choices=[('lessons', 'Nach Terminen'), ('date', 'Bis Datum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='temporarytutorassignment',
            name='ended_reason',
            field=models.CharField(blank=True, choices=[('lessons_reached', 'Termine erreicht'), ('date_reached', 'Enddatum erreicht'), ('handover', 'Abgabe'), ('superseded', 'Überschrieben')], max_length=30),
        ),
    ]
