# Generated by Django 4.2.26 on 2026-03-31 19:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_temporarytutorassignment_end_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('importance', models.CharField(choices=[('prio', 'prio'), ('normal', 'normal'), ('idee', 'idee')], default='normal', max_length=20)),
                ('days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('status', models.CharField(choices=[('todo', 'to do'), ('doing', 'doing'), ('done', 'done')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_tasks', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='owned_admin_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin-Aufgabe',
                'verbose_name_plural': 'Admin-Aufgaben',
                'ordering': ['status', 'created_at'],
            },
        ),
    ]
