# Generated by Django 4.2.26 on 2026-03-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_admintask'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutortemplate',
            name='visibility',
            field=models.CharField(choices=[('tutors', 'TutorInnen'), ('admins', 'Admins'), ('both', 'TutorInnen und Admins')], default='both', max_length=20),
        ),
    ]
