# Generated by Django 4.2.26 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_tutortemplate_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("parent", "Elternteil"), ("student", "SchülerIn"), ("tutor", "TutorIn")], max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("preferred_contact", models.CharField(choices=[("whatsapp", "WhatsApp"), ("phone", "Telefon"), ("email", "E-Mail")], max_length=20)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("grade", models.CharField(blank=True, max_length=120)),
                ("tutoring_type", models.CharField(choices=[("online", "Online"), ("in_person", "Vor Ort"), ("both", "Beides")], max_length=20)),
                ("goal", models.CharField(blank=True, max_length=255)),
                ("urgency", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("new", "Neu"), ("contacted", "Kontaktiert"), ("appointment_planned", "Termin geplant"), ("won", "Gewonnen"), ("lost", "Verloren"), ("unsuitable", "Unpassend")], default="new", max_length=30)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("campaign", models.CharField(blank=True, max_length=120)),
                ("utm_source", models.CharField(blank=True, max_length=120)),
                ("utm_medium", models.CharField(blank=True, max_length=120)),
                ("utm_campaign", models.CharField(blank=True, max_length=120)),
                ("utm_content", models.CharField(blank=True, max_length=120)),
                ("utm_term", models.CharField(blank=True, max_length=120)),
                ("privacy_consent", models.BooleanField(default=False)),
                ("education_status", models.CharField(blank=True, choices=[("upper_school", "SchülerIn Oberstufe"), ("student", "StudentIn"), ("teacher", "Lehrkraft"), ("professional", "Berufstätig"), ("other", "Sonstiges")], max_length=30)),
                ("teaching_subjects", models.CharField(blank=True, max_length=255)),
                ("teaching_grades", models.CharField(blank=True, max_length=255)),
                ("weekly_availability", models.CharField(blank=True, max_length=120)),
                ("experience_level", models.CharField(blank=True, choices=[("none", "Noch keine Erfahrung"), ("some", "Etwas Erfahrung"), ("regular", "Regelmäßig Nachhilfe gegeben"), ("professional", "Professionelle Unterrichtserfahrung")], max_length=30)),
                ("motivation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
