# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="referrer",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="lead",
            name="landing_page_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="lead",
            name="initial_querystring",
            field=models.TextField(blank=True),
        ),
    ]
