# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_lead_attribution_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_status_change_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="follow_up_done",
            field=models.BooleanField(default=False),
        ),
    ]
