# Generated by Codex on 2026-05-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_lead_pipeline_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vision", "große Ideen/Vision"),
                            ("improvement", "kleine Ideen, Verbesserungen"),
                        ],
                        default="improvement",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin-Idee",
                "verbose_name_plural": "Admin-Ideen",
                "ordering": ["category", "-created_at"],
            },
        ),
    ]
