# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_adminidea"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminidea",
            name="image",
            field=models.ImageField(blank=True, upload_to="admin_ideas/%Y/%m/"),
        ),
    ]
