# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_adminidea_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="image",
            field=models.ImageField(blank=True, upload_to="admin_tasks/%Y/%m/"),
        ),
    ]
