# Generated by Django 4.2.26 on 2026-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_admintask_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='affected_courses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='degree_program',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tutoring_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'SchülerIn'), ('independent_student', 'StudentIn'), ('parent', 'Parent'), ('tutor', 'TutorIn')], default='student', max_length=20),
        ),
    ]
