# Generated by Django 4.2.26 on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_studentprofile_affected_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminidea",
            name="title",
            field=models.TextField(),
        ),
    ]
