# Generated by Django 4.2.26 on 2026-06-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_faqitem_spanish_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='longitude',
        ),
    ]
