# Generated by Django 4.2.26 on 2026-06-09 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_studentprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_tutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='core.tutorprofile'),
        ),
    ]
