# Generated by Django 4.2.26 on 2026-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_lead_converted_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintask',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
