# Generated by Django 4.2.26 on 2026-06-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_admintask_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='created_by_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to='core.tutorprofile'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='bbb_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='self_employment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='status',
            field=models.CharField(choices=[('beworben', 'beworben'), ('eingeladen', 'eingeladen'), ('kennengelernt', 'kennengelernt'), ('akzeptiert', 'akzeptiert'), ('abgelehnt', 'abgelehnt'), ('onboarding', 'onboarding'), ('aktiv', 'aktiv')], default='aktiv', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
