# Generated by Django 4.2.26 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_studentprofile_created_by_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='tax_number_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='status',
            field=models.CharField(choices=[('beworben', 'beworben'), ('eingeladen', 'eingeladen'), ('kennengelernt', 'kennengelernt'), ('akzeptiert', 'akzeptiert'), ('abgelehnt', 'abgelehnt'), ('onboarding', 'onboarding'), ('aktiv', 'aktiv'), ('pausiert', 'pausiert')], default='aktiv', max_length=20),
        ),
    ]
