# Generated by Django 4.2.26 on 2026-06-17 11:48

from django.db import migrations, models


def _format_profile_number(prefix, sequence):
    serial = f"{sequence:06d}"
    return f"{prefix}-{serial[:3]}-{serial[3:]}"


def populate_profile_numbers(apps, schema_editor):
    ParentProfile = apps.get_model("core", "ParentProfile")
    StudentProfile = apps.get_model("core", "StudentProfile")
    TutorProfile = apps.get_model("core", "TutorProfile")

    for index, parent in enumerate(ParentProfile.objects.order_by("id"), start=1):
        if not parent.customer_number:
            parent.customer_number = _format_profile_number("ELT", index)
            parent.save(update_fields=["customer_number"])

    student_counter = 0
    independent_student_counter = 0
    for student in StudentProfile.objects.select_related("user").order_by("id"):
        if student.profile_number:
            continue
        if student.user.role == "independent_student":
            independent_student_counter += 1
            student.profile_number = _format_profile_number("STUD", independent_student_counter)
        else:
            student_counter += 1
            student.profile_number = _format_profile_number("SCHU", student_counter)
        student.save(update_fields=["profile_number"])

    for index, tutor in enumerate(TutorProfile.objects.order_by("id"), start=1):
        if not tutor.tutor_number:
            tutor.tutor_number = _format_profile_number("TUT", index)
            tutor.save(update_fields=["tutor_number"])


def clear_profile_numbers(apps, schema_editor):
    apps.get_model("core", "ParentProfile").objects.update(customer_number=None)
    apps.get_model("core", "StudentProfile").objects.update(profile_number=None)
    apps.get_model("core", "TutorProfile").objects.update(tutor_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_tutorprofile_tax_number_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='customer_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='tutor_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.RunPython(populate_profile_numbers, clear_profile_numbers),
    ]
