# Generated by Django 4.2.26 on 2026-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_parentprofile_customer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_email_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
