# Generated by Django 4.2.26 on 2026-09-01 11:55

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_customuser_pending_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('learning', 'Lernvereinbarung'), ('tutor', 'TutorInnenvereinbarung')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending_participant', 'Wartet auf VertragspartnerIn'), ('pending_email', 'Wartet auf E-Mail-Bestätigung'), ('pending_brainboost', 'Wartet auf BrainBoost'), ('completed', 'Abgeschlossen'), ('declined', 'Abgelehnt'), ('revoked', 'Widerrufen'), ('superseded', 'Ersetzt')], default='draft', max_length=30)),
                ('version', models.CharField(default='draft-1', max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('terms_snapshot', models.TextField()),
                ('data_snapshot', models.JSONField(default=dict)),
                ('payment_method', models.CharField(blank=True, choices=[('', 'Noch nicht gewählt'), ('cash', 'Bargeld'), ('stripe_sepa', 'SEPA-Lastschrift über Stripe')], default='', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('participant_name', models.CharField(blank=True, max_length=255)),
                ('participant_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('brainboost_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token_digest', models.CharField(blank=True, max_length=64)),
                ('confirmation_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('final_pdf', models.FileField(blank=True, upload_to=core.models.agreement_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('final_pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('brainboost_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brainboost_confirmed_agreements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agreements', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to=settings.AUTH_USER_MODEL)),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='core.lead')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.studentprofile')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_agreements', to='core.tutorprofile')),
            ],
            options={
                'verbose_name': 'Vereinbarung',
                'verbose_name_plural': 'Vereinbarungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_audit_events', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.agreement')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['participant', 'status'], name='core_agreem_partici_d11d25_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['agreement_type', 'status'], name='core_agreem_agreeme_3bf03d_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('agreement_type', 'tutor'), ('student__isnull', True)), ('agreement_type', 'learning'), _connector='OR'), name='tutor_agreement_has_no_student'),
        ),
    ]
