# Generated by Django 4.2.26 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_agreement_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='stripe_mandate_status',
            field=models.CharField(blank=True, choices=[('', 'Nicht eingerichtet'), ('pending', 'Einrichtung läuft'), ('active', 'Aktiv'), ('failed', 'Fehlgeschlagen')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agreement',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
