# Generated by Django 5.2.16 on 2026-09-25 11:22

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_lead_appointment_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(core.models.current_year)], verbose_name='Geburtsjahr'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_state',
            field=models.CharField(blank=True, choices=[('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('BE', 'Berlin'), ('BB', 'Brandenburg'), ('HB', 'Bremen'), ('HH', 'Hamburg'), ('HE', 'Hessen'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('SH', 'Schleswig-Holstein'), ('TH', 'Thüringen')], max_length=2, verbose_name='Bundesland der Schule'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Schulform'),
        ),
    ]
