# Generated by Django 4.2.26 on 2026-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_agreement_stripe_mandate_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='participant_consents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
