# Generated by Django 6.1.1 on 2026-09-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_student_school_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='waitlist_previous_tutor_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='waitlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('appointment_planned', 'Termin geplant'), ('won', 'Gewonnen'), ('lost', 'Verloren'), ('unsuitable', 'Unpassend'), ('waitlisted', 'Warteliste'), ('availability_requested', 'Verfügbarkeit angefragt'), ('interested', 'Interesse bestätigt')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='status',
            field=models.CharField(choices=[('beworben', 'beworben'), ('eingeladen', 'eingeladen'), ('kennengelernt', 'kennengelernt'), ('akzeptiert', 'akzeptiert'), ('abgelehnt', 'abgelehnt'), ('warteliste', 'Warteliste'), ('onboarding', 'onboarding'), ('aktiv', 'aktiv'), ('pausiert', 'pausiert')], default='aktiv', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadStatusEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('contacted', 'Kontaktiert'), ('appointment_planned', 'Termin geplant'), ('won', 'Gewonnen'), ('lost', 'Verloren'), ('unsuitable', 'Unpassend'), ('waitlisted', 'Warteliste'), ('availability_requested', 'Verfügbarkeit angefragt'), ('interested', 'Interesse bestätigt')], max_length=30)),
                ('status_changed_at', models.DateTimeField()),
                ('recipient', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_emails', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lead', 'status_changed_at'), name='unique_lead_status_email')],
            },
        ),
    ]
