# Generated by Django 4.2.26 on 2026-09-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_agreement_participant_consents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='tutor_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tutor_confirmation_token_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tutor_confirmation_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tutor_consents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tutor_email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('pending_participant', 'Wartet auf VertragspartnerIn'), ('pending_email', 'Wartet auf E-Mail-Bestätigung'), ('pending_tutor', 'Wartet auf TutorIn'), ('pending_tutor_email', 'Wartet auf TutorInnen-E-Mail'), ('pending_brainboost', 'Wartet auf BrainBoost'), ('completed', 'Abgeschlossen'), ('declined', 'Abgelehnt'), ('revoked', 'Widerrufen'), ('superseded', 'Ersetzt')], default='draft', max_length=30),
        ),
    ]
