# Generated by Django 6.1.1 on 2026-09-28 17:38

import django.db.models.deletion
from django.db import migrations, models


def migrate_numbers(apps, schema_editor):
    """Snapshot of initial allocation; do not depend on future application code."""
    from django.utils import timezone

    using = schema_editor.connection.alias
    Tutor = apps.get_model("core", "TutorProfile")
    Reservation = apps.get_model("core", "TutorNumberReservation")
    Lock = apps.get_model("core", "TutorNumberLock")
    tutors = list(Tutor.objects.using(using).select_related("user").order_by("pk"))
    kiaras = [t.pk for t in tutors if
              (t.user.first_name.strip().casefold(), t.user.last_name.strip().casefold())
              == ("kiara", "puppe")]
    if len(kiaras) > 1:
        raise RuntimeError(
            "Mehrere Konten für Kiara Puppe gefunden. Vor der Migration eindeutig zuordnen."
        )
    kiara = kiaras[0] if kiaras else None
    through = Tutor.assigned_tutors.through

    # Legacy data allowed Kiara to be selected as somebody else's subordinate.
    # The new hierarchy defines her as its root, so those incoming edges cannot
    # be retained. Outgoing assignments from Kiara remain untouched.
    if kiara is not None:
        through.objects.using(using).filter(to_tutorprofile_id=kiara).delete()
    parents = {}
    for parent, child in through.objects.using(using).values_list(
        "from_tutorprofile_id", "to_tutorprofile_id"
    ):
        if child in parents:
            raise RuntimeError(f"TutorIn {child} hat mehrere übergeordnete TutorInnen. Zuordnung zuerst bereinigen.")
        parents[child] = parent
    for child in parents:
        seen = set()
        node = child
        while node in parents:
            if node in seen:
                raise RuntimeError("Kreis in TutorInnenzuordnungen. Zuordnung zuerst bereinigen.")
            seen.add(node)
            node = parents[node]

    # Calculate the complete result before changing any existing data.
    numbers = {}
    counters = {"TUT": 1}  # TUT1 is permanently reserved for Kiara.
    pending = {t.pk for t in tutors}
    while pending:
        for pk in sorted(pending):
            parent = parents.get(pk)
            if parent is not None and parent not in numbers:
                continue
            if pk == kiara:
                numbers[pk] = "TUT1"
            else:
                prefix = f"{numbers[parent]}-" if parent is not None else "TUT"
                counters[prefix] = counters.get(prefix, 0) + 1
                numbers[pk] = f"{prefix}{counters[prefix]}"
            if len(numbers[pk]) > 255:
                raise RuntimeError("TutorInnenhierarchie ist zu tief für die Nummernvergabe.")
            pending.remove(pk)
    Lock.objects.using(using).get_or_create(pk=1)
    now = timezone.now()
    for tutor in tutors:
        if tutor.tutor_number and tutor.tutor_number != numbers[tutor.pk]:
            Reservation.objects.using(using).create(
                number=tutor.tutor_number, tutor_id=tutor.pk,
                original_tutor_id=tutor.pk, archived_at=now,
            )
    Tutor.objects.using(using).update(tutor_number=None)
    for tutor in tutors:
        number = numbers[tutor.pk]
        if Reservation.objects.using(using).filter(number=number).exists():
            raise RuntimeError(f"Die neue Nummer {number} ist bereits historisch belegt.")
        Reservation.objects.using(using).create(
            number=number, tutor_id=tutor.pk, original_tutor_id=tutor.pk,
        )
        Tutor.objects.using(using).filter(pk=tutor.pk).update(tutor_number=number)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_tutor_application_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorNumberLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutor_number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TutorNumberReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('original_tutor_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tutorprofile')),
            ],
            options={
                'verbose_name': 'TutorInnenbezeichnung (Reservierung)',
                'verbose_name_plural': 'TutorInnenbezeichnungen (Archiv)',
            },
        ),
        migrations.RunPython(migrate_numbers),
    ]
