# Generated by Django 4.2.26 on 2026-09-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_agreement_tutor_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_closure_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_closure_token_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customuser",
            name="account_closure_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="scheduled_deletion_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="terminated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="termination_effective_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to="core.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="counterparty_agreements",
                to="core.tutorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Entwurf"),
                    ("pending_participant", "Wartet auf VertragspartnerIn"),
                    ("pending_email", "Wartet auf E-Mail-Bestätigung"),
                    ("pending_tutor", "Wartet auf TutorIn"),
                    ("pending_tutor_email", "Wartet auf TutorInnen-E-Mail"),
                    ("pending_brainboost", "Wartet auf BrainBoost"),
                    ("completed", "Abgeschlossen"),
                    ("terminated", "Gekündigt"),
                    ("declined", "Abgelehnt"),
                    ("revoked", "Widerrufen"),
                    ("superseded", "Ersetzt"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="stripe_mandate_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nicht eingerichtet"),
                    ("pending", "Einrichtung läuft"),
                    ("active", "Aktiv"),
                    ("inactive", "Beendet"),
                    ("failed", "Fehlgeschlagen"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
