# Generated by Django 6.1.1 on 2026-09-28 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_hierarchical_tutor_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=255)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('role_snapshot', models.CharField(choices=[('student', 'SchülerIn'), ('independent_student', 'StudentIn'), ('parent', 'Parent'), ('tutor', 'TutorIn')], max_length=20)),
                ('delete_account', models.BooleanField(default=False)),
                ('terminate_agreement', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Beantragt'), ('confirmed', 'Von BrainBoost bestätigt'), ('completed', 'Abgeschlossen'), ('rejected', 'Abgelehnt')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_cancellation_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kündigungs-/Löschantrag',
                'verbose_name_plural': 'Kündigungs-/Löschanträge',
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'confirmed'])), fields=('user',), name='one_open_cancellation_request_per_user'), models.CheckConstraint(condition=models.Q(('delete_account', True), ('terminate_agreement', True), _connector='OR'), name='cancellation_request_has_action')],
            },
        ),
    ]
