# Generated by Django 6.1.1 on 2026-10-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_cancellation_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_weekdays',
            field=models.JSONField(blank=True, default=list, verbose_name='Bevorzugte Wochentage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße (ohne Hausnummer)'),
        ),
    ]
